### ISSUE TITLE
Required guzzlehttp/psr7 doesn't support PHP 8.1

### ISSUE THREAD

**Issue by ftibensky** [GetResponse/sdk-php-client#5]
Even though this project was [updated for PHP 8.1](https://github.com/GetResponse/sdk-php-client/commit/943c5bf944b0f85872a13759d671c44ecdbf4285), it still requires `"guzzlehttp/psr7": "^1.4"` [which doesn't support PHP 8.1](https://github.com/guzzle/psr7#version-guidance).
A project I'm working on uses `guzzlehttp/psr7` and `getresponse/sdk-php` and this is blocking us from updating to psr7 2.x.
Seems like some others are also having this problem, since there are already some forks trying to address this, like https://github.com/b2bcenter/sdk-php-client and https://github.com/naturalGroove/getresponse-sdk-php-client.

**Comment by dfumagalli** [comment]
I have the same problem. Current Laravel is using Guzzle 2.5 and won't install the sdk-client.

**Comment by ant-magic42** [comment]
I also have this problem

**Comment by dfumagalli** [comment]
Go to [my Github repos](https://github.com/dfumagalli), I've upgraded all the libraries to work with the new PHP, Guzzle, Laravel etc.

I also uploaded these repos to Packagist, so you can directly use them from `composer require`.

**Comment by thedotedge** [comment]
@slavGR any chance to get this integrated into main package?

**Comment by thedotedge** [comment]
@dfumagalli any chance you could publish https://github.com/dfumagalli/sdk-php to Packagist as well? Can't seem to find it 🙈

**Comment by slavGR** [comment]
> @slavGR any chance to get this integrated into main package?

Hi @thedotedge , we're on it. Thanks for your feedback.

**Comment by thedotedge** [comment]
@slavGR great, happy to hear this 👍🏻 Any ETA for the new version?

**Comment by dfumagalli** [comment]
> @dfumagalli any chance you could publish https://github.com/dfumagalli/sdk-php to Packagist as well? Can't seem to find it 🙈

It's internally required by the getresponse package, so you don't need it published on Packagist.
If for some reason you really need the sdk-php, open the getresponse package and copy-paste in your composer.json file the stanza that includes the sdk-php.

**Comment by mfadul24** [comment]
Please review and release: https://github.com/GetResponse/sdk-php-client/pull/6

Thanks in advance

**Comment by slavGR** [comment]
Hi there, thank you for your contribution. We have released an upgrade due to a new version of guzzlehttp/psr7 to comply with php >=8.1 as per your request. We still aim to support php >= 7.3.
https://github.com/GetResponse/sdk-php-client/releases/tag/2.0.1

**Comment by Adricz22** [comment]
Hello @GetResponse 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---

**Comment by Adricz22** [comment]
Hello @GetResponse 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---
